// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `LogModelGeneratorConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost;Initial Catalog=ModactLog;Integrated Security=true;`
//     Include Views:          `False`

//using System;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using System.Collections.Generic;
using Dapper.SimpleCRUD;

namespace Modact.Data.Models
{
    /// <summary>
    /// A class which represents the log_api_connect table.
    /// </summary>
	[Table("log_api_connect")]
	public partial class DTO_log_api_connect : IDto
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? id_parent { get; set; }
		public virtual string? app_id { get; set; }
		public virtual string? app_name { get; set; }
		public virtual string? app_machine_name { get; set; }
		public virtual string? app_node_id { get; set; }
		public virtual string? app_version { get; set; }
		public virtual string? modact_version { get; set; }
		public virtual DateTime? start_time { get; set; }
		public virtual double? process_second { get; set; }
		public virtual bool? is_success { get; set; }
		public virtual string? fatal_msg { get; set; }
		public virtual bool? is_send_request { get; set; }
		public virtual string? request_url { get; set; }
		public virtual string? request_http_method { get; set; }
		public virtual string? request_origin_url { get; set; }
		public virtual string? request_app_id { get; set; }
		public virtual string? request_app_name { get; set; }
		public virtual string? request_app_version { get; set; }
		public virtual string? request_client_type { get; set; }
		public virtual string? request_client_name { get; set; }
		public virtual string? request_ip { get; set; }
		public virtual string? request_mac_address { get; set; }
		public virtual string? request_agent { get; set; }
		public virtual string? response_app_id { get; set; }
		public virtual string? response_app_version { get; set; }
		public virtual string? auth_id { get; set; }
		public virtual string? user_id { get; set; }
		public virtual string? user_name { get; set; }
		public virtual double? start_cpu_usage { get; set; }
		public virtual double? end_cpu_usage { get; set; }
		public virtual double? start_memory_usage_mb { get; set; }
		public virtual double? end_memory_usage_mb { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_connect_context table.
    /// </summary>
	[Table("log_api_connect_context")]
	public partial class DTO_log_api_connect_context : IDto
	{
		[Key]
		public virtual string? api_connect_id { get; set; }
		public virtual string? request_body { get; set; }
		public virtual string? response_body { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_request table.
    /// </summary>
	[Table("log_api_request")]
	public partial class DTO_log_api_request : IDto
	{
		[Key]
		public virtual string? api_connect_id { get; set; }
		public virtual string? request_id { get; set; }
		public virtual DateTime? request_time { get; set; }
		public virtual int? action_count { get; set; }
		public virtual int? async_action_count { get; set; }
		public virtual int? function_count { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_request_function table.
    /// </summary>
	[Table("log_api_request_function")]
	public partial class DTO_log_api_request_function : IDto
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? api_connect_id { get; set; }
		public virtual string? action_type { get; set; }
		public virtual bool? is_async { get; set; }
		public virtual bool? is_trans { get; set; }
		public virtual int? action_order { get; set; }
		public virtual int? fun_order { get; set; }
		public virtual string? fun_id { get; set; }
		public virtual string? fun_name { get; set; }
		public virtual bool? is_success { get; set; }
		public virtual DateTime? start_time { get; set; }
		public virtual double? process_second { get; set; }
		public virtual double? start_cpu_usage { get; set; }
		public virtual double? end_cpu_usage { get; set; }
		public virtual double? start_memory_usage_mb { get; set; }
		public virtual double? end_memory_usage_mb { get; set; }
		public virtual string? api_function { get; set; }
		public virtual string? result_data { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_response table.
    /// </summary>
	[Table("log_api_response")]
	public partial class DTO_log_api_response : IDto
	{
		[Key]
		public virtual string? api_connect_id { get; set; }
		public virtual string? response_id { get; set; }
		public virtual string? request_id { get; set; }
		public virtual DateTime? response_time { get; set; }
		public virtual int? success_count { get; set; }
		public virtual int? fatal_count { get; set; }
		public virtual int? error_count { get; set; }
		public virtual int? warn_count { get; set; }
		public virtual int? message_count { get; set; }
		public virtual int? result_count { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_response_message table.
    /// </summary>
	[Table("log_api_response_message")]
	public partial class DTO_log_api_response_message : IDto
	{
		[Key]
		public virtual string? api_connect_id { get; set; }
		public virtual string? messages { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_response_result table.
    /// </summary>
	[Table("log_api_response_result")]
	public partial class DTO_log_api_response_result : IDto
	{
		[Key]
		public virtual string? api_connect_id { get; set; }
		public virtual string? results { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

    /// <summary>
    /// A class which represents the log_api_token_error table.
    /// </summary>
	[Table("log_api_token_error")]
	public partial class DTO_log_api_token_error : IDto
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? api_connect_id { get; set; }
		public virtual string? authorization_raw { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	}

}
