// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ModactModelGeneratorConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost;Initial Catalog=Modact;Integrated Security=true;`
//     Include Views:          `False`

//using System;
//using System.ComponentModel.DataAnnotations;
//using System.ComponentModel.DataAnnotations.Schema;
//using System.Collections.Generic;
using Dapper.SimpleCRUD;

namespace Modact.Data.Models
{
    /// <summary>
    /// A class which represents the modm_app table.
    /// </summary>
	[Table("modm_app")]
	public partial class DTO_modm_app : IMasterTableDto 
	{
		[Key]
		public virtual string? app_id { get; set; }
		public virtual string? app_secret { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_appnode table.
    /// </summary>
	[Table("modm_appnode")]
	public partial class DTO_modm_appnode : IMasterTableDto 
	{
		[Key]
		public virtual string? app_node_id { get; set; }
		public virtual string? base_url { get; set; }
		public virtual bool? is_standby { get; set; }
		public virtual int? priority { get; set; }
		public virtual int? connections { get; set; }
		public virtual DateTime? last_connect_time { get; set; }
		public virtual DateTime? last_connect_time_utc { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_config table.
    /// </summary>
	[Table("modm_config")]
	public partial class DTO_modm_config : IMasterTableDto 
	{
		[Key]
		public virtual string? config_code { get; set; }
		public virtual string? config_value { get; set; }
		public virtual string? config_value_default { get; set; }
		public virtual string? config_type_id { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_configtype table.
    /// </summary>
	[Table("modm_configtype")]
	public partial class DTO_modm_configtype : IMasterTableDto 
	{
		[Key]
		public virtual string? config_type_id { get; set; }
		public virtual string? config_type_name { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_device table.
    /// </summary>
	[Table("modm_device")]
	public partial class DTO_modm_device : IMasterTableDto 
	{
		[Key]
		public virtual string? device_id { get; set; }
		public virtual string? device_name { get; set; }
		public virtual string? device_type_id { get; set; }
		public virtual string? ip { get; set; }
		public virtual string? mac_address { get; set; }
		public virtual string? machine_code { get; set; }
		public virtual string? machine_name { get; set; }
		public virtual bool? is_black_list { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_devicetype table.
    /// </summary>
	[Table("modm_devicetype")]
	public partial class DTO_modm_devicetype : IMasterTableDto 
	{
		[Key]
		public virtual string? device_type_id { get; set; }
		public virtual string? device_type_name { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_license table.
    /// </summary>
	[Table("modm_license")]
	public partial class DTO_modm_license : IMasterTableDto 
	{
		[Key]
		public virtual string? license_id { get; set; }
		public virtual string? license_data { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_permission table.
    /// </summary>
	[Table("modm_permission")]
	public partial class DTO_modm_permission : IMasterTableDto 
	{
		[Key]
		public virtual string? permission_code { get; set; }
		public virtual string? permission_desc { get; set; }
		public virtual string? permission_type_id { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_permissiontype table.
    /// </summary>
	[Table("modm_permissiontype")]
	public partial class DTO_modm_permissiontype : IMasterTableDto 
	{
		[Key]
		public virtual string? permission_type_id { get; set; }
		public virtual string? permission_type_name { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_role table.
    /// </summary>
	[Table("modm_role")]
	public partial class DTO_modm_role : IMasterTableDto 
	{
		[Key]
		public virtual string? role_id { get; set; }
		public virtual string? role_name { get; set; }
		public virtual bool? is_system { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_serialnumber table.
    /// </summary>
	[Table("modm_serialnumber")]
	public partial class DTO_modm_serialnumber : IMasterTableDto 
	{
		[Key]
		public virtual string? sn_id { get; set; }
		public virtual string? sn_name { get; set; }
		public virtual string? sn_prefix { get; set; }
		public virtual string? sn_postfix { get; set; }
		public virtual decimal? sn_number { get; set; }
		public virtual decimal? sn_begin { get; set; }
		public virtual decimal? sn_end { get; set; }
		public virtual decimal? sn_step { get; set; }
		public virtual bool? is_rollover { get; set; }
		public virtual string? padding_char { get; set; }
		public virtual int? padding_digit { get; set; }
		public virtual string? reset_by_datetime { get; set; }
		public virtual string? last_sn_datetime_value { get; set; }
		public virtual DateTime? last_sn_create_time { get; set; }
		public virtual string? remark { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_token_jwt table.
    /// </summary>
	[Table("modm_token_jwt")]
	public partial class DTO_modm_token_jwt : IMasterTableDto 
	{
		[Key]
		public virtual string? jwt_id { get; set; }
		public virtual bool? is_asymmetric { get; set; }
		public virtual string? private_key_path { get; set; }
		public virtual string? public_key_path { get; set; }
		public virtual string? secret { get; set; }
		public virtual string? issuer { get; set; }
		public virtual string? audience { get; set; }
		public virtual int? expire_minute { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modm_token_user table.
    /// </summary>
	[Table("modm_token_user")]
	public partial class DTO_modm_token_user : IMasterTableDto 
	{
		[Key]
		public virtual string? user_id { get; set; }
		public virtual string? user_name { get; set; }
		public virtual string? user_group { get; set; }
		public virtual string? user_meta { get; set; }
		public virtual string? last_auth_id { get; set; }
		public virtual DateTime? last_auth_time { get; set; }
		public virtual string? last_token_id { get; set; }
		public virtual string? last_log_id { get; set; }
		public virtual DateTime? last_session_time { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modr_device_permission table.
    /// </summary>
	[Table("modr_device_permission")]
	public partial class DTO_modr_device_permission : IRelationalTableDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? device_id { get; set; }
		public virtual string? role_id { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modr_device_user table.
    /// </summary>
	[Table("modr_device_user")]
	public partial class DTO_modr_device_user : IRelationalTableDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? device_id { get; set; }
		public virtual string? role_id { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modr_role_permission table.
    /// </summary>
	[Table("modr_role_permission")]
	public partial class DTO_modr_role_permission : IRelationalTableDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? role_id { get; set; }
		public virtual string? permission_code { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modr_role_user table.
    /// </summary>
	[Table("modr_role_user")]
	public partial class DTO_modr_role_user : IRelationalTableDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? role_id { get; set; }
		public virtual string? user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modr_role_usergroup table.
    /// </summary>
	[Table("modr_role_usergroup")]
	public partial class DTO_modr_role_usergroup : IRelationalTableDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual string? role_id { get; set; }
		public virtual string? user_group_id { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	}

    /// <summary>
    /// A class which represents the modt_token_session table.
    /// </summary>
	[Table("modt_token_session")]
	public partial class DTO_modt_token_session : ITransactionDto 
	{
		[Key]
		public virtual string? id { get; set; }
		public virtual bool? is_user { get; set; }
		public virtual string? user_id { get; set; }
		public virtual string? user_name { get; set; }
		public virtual string? access_token_id { get; set; }
		public virtual DateTime? access_token_expiry { get; set; }
		public virtual string? refresh_token_id { get; set; }
		public virtual DateTime? refresh_token_expiry { get; set; }
		public virtual string? device_id { get; set; }
		public virtual string? ip { get; set; }
		public virtual string? mac_address { get; set; }
		public virtual string? machine_code { get; set; }
		public virtual string? machine_name { get; set; }
		public virtual string? last_log_id { get; set; }
		public virtual DateTime? last_connect_time { get; set; }
		public virtual DateTime? last_session_time { get; set; }
	 
		[IgnoreInsert]
		public virtual bool? is_void { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? void_switch_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_switch_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? void_remark { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time { get; set; }
	 
		[IgnoreUpdate]
		public virtual DateTime? create_time_utc { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_id { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_user_name { get; set; }
	 
		[IgnoreUpdate]
		public virtual string? create_log_id { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time { get; set; }
	 
		[IgnoreInsert]
		public virtual DateTime? modify_time_utc { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_id { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_user_name { get; set; }
	 
		[IgnoreInsert]
		public virtual string? modify_log_id { get; set; }
	}

}
